export const ACTIVITY_OUTPUT_FIELDS = [
  "date",
  "sport",
  "durationSeconds",
  "distanceMeters",
  "elevationGainMeters",
  "trainingLoad",
  "intensity",
  "averageHeartRate",
  "maximumHeartRate",
  "averagePower",
  "normalizedPower",
  "cadence",
  "aerobicDecoupling",
  "trimp",
  "heartRateLoad",
  "modeledFtp",
  "efficiencyFactor",
] as const;

export const FORBIDDEN_OUTPUT_KEY_FRAGMENTS = [
  "lat",
  "lng",
  "latitude",
  "longitude",
  "map",
  "route",
  "polyline",
  "token",
  "authorization",
  "fit",
  "gpx",
  "tcx",
  "address",
] as const;
